### ISSUE TITLE
Improve cli hotkeys to support OSX better

### ISSUE THREAD

**Issue by cblgh** [cabal-club/cabal#91]
we're using `alt` as a modifier, and it's not behaving as intended on OSX

### Tasks
- [ ] experiment on OSX and pinpoint what's weird
- [ ] look into how [keypress ](https://github.com/TooTallNate/keypress)works
- [ ] look into patching functionality upstream in either [neat-input ](https://github.com/mafintosh/neat-input) or [keypress](https://github.com/TooTallNate/keypress)
- [ ] use a new modifier if all else fails
- [ ] rethink hotkey usage

**Comment by rinchen** [comment]
https://github.com/dd-pardal/tty-events might be another option.

**Comment by noffle** [comment]
It could be a configuration issue. As I remember, the default Terminal.app needs a config bit flipped to allow the Alt key to be accepted.
